export const INITIAL_EXPENSES = [
  {
    id: 'exp-1',
    title: 'Assicurazione RC Auto',
    amount: 540,
    category: 'vehicle',
    frequency: 'annual',
    profileId: 'p3',
    nextDueDate: '2026-11-20',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-2',
    title: 'Bollo Auto',
    amount: 220,
    category: 'vehicle',
    frequency: 'annual',
    profileId: 'p3',
    nextDueDate: '2027-01-31',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-3',
    title: 'Manutenzione Caldaia & Bollino',
    amount: 120,
    category: 'home',
    frequency: 'annual',
    profileId: 'p2',
    nextDueDate: '2026-10-10',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-4',
    title: 'Abbonamento Annuale Prime',
    amount: 49.90,
    category: 'subscriptions',
    frequency: 'annual',
    profileId: 'p1',
    nextDueDate: '2026-12-15',
    enableAlert: true,
    includeInCalendar: false,
    status: 'due',
  },
  {
    id: 'exp-5',
    title: 'Fibra Internet Casa',
    amount: 29.90,
    category: 'utilities',
    frequency: 'monthly',
    profileId: 'p2',
    nextDueDate: '2026-10-05',
    enableAlert: false,
    includeInCalendar: false,
    status: 'due',
  },
  {
    id: 'exp-6',
    title: 'Energia Elettrica / Luce',
    amount: 85,
    category: 'utilities',
    frequency: 'bimonthly',
    profileId: 'p2',
    nextDueDate: '2026-10-15',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
    isVariable: true,
    contract: {
      name: 'Octopus Energy - Tariffa Fissa',
      startDate: '2026-03-01',
      estimatedAmount: 85,
    },
    paymentHistory: [
      { id: 'bill-1', date: '2026-04-10', amount: 82.50, note: 'Bolletta Mar-Apr' },
      { id: 'bill-2', date: '2026-06-12', amount: 87.50, note: 'Bolletta Mag-Giu' },
    ],
  },
];
