export const SEED_PERSONAL_EXPENSES = [
  {
    id: 'exp-1',
    title: 'Assicurazione RC Auto',
    amount: 540,
    category: 'insurance',
    frequency: 'annual',
    profileId: 'p1',
    nextDueDate: '2026-11-20',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-2',
    title: 'Bollo Auto',
    amount: 210,
    category: 'taxes',
    frequency: 'annual',
    profileId: 'p1',
    nextDueDate: '2027-01-31',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-3',
    title: 'Revisione Auto',
    amount: 79,
    category: 'vehicle',
    frequency: 'biennial',
    profileId: 'p1',
    nextDueDate: '2027-05-15',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-4',
    title: 'Palestra',
    amount: 420,
    category: 'sport',
    frequency: 'annual',
    profileId: 'p1',
    nextDueDate: '2026-10-15',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-5',
    title: 'Polizza Infortuni',
    amount: 160,
    category: 'health',
    frequency: 'semiannual',
    profileId: 'p1',
    nextDueDate: '2026-12-10',
    enableAlert: true,
    includeInCalendar: false,
    status: 'due',
  },
];
