export const SEED_HOME_EXPENSES = [
  {
    id: 'exp-6',
    title: 'Tassa Rifiuti TARI',
    amount: 145,
    category: 'taxes',
    frequency: 'semiannual',
    profileId: 'p2',
    nextDueDate: '2026-10-31',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-7',
    title: 'Manutenzione Caldaia',
    amount: 120,
    category: 'home',
    frequency: 'annual',
    profileId: 'p2',
    nextDueDate: '2026-10-15',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-8',
    title: 'Assicurazione Fabbricato',
    amount: 280,
    category: 'insurance',
    frequency: 'annual',
    profileId: 'p2',
    nextDueDate: '2026-11-05',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-9',
    title: 'Condominio',
    amount: 220,
    category: 'home',
    frequency: 'quarterly',
    profileId: 'p2',
    nextDueDate: '2026-12-01',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-10',
    title: 'Energia Elettrica',
    amount: 85,
    category: 'utilities',
    frequency: 'bimonthly',
    profileId: 'p2',
    nextDueDate: '2026-10-20',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
    isVariable: true,
    contract: { name: 'Tariffa Luce Fissa', startDate: '2026-03-01', estimatedAmount: 85 },
    paymentHistory: [
      { id: 'bill-1', date: '2026-04-10', amount: 82.5, note: 'Luce Mar-Apr' },
      { id: 'bill-2', date: '2026-06-12', amount: 87.5, note: 'Luce Mag-Giu' },
    ],
  },
  {
    id: 'exp-11',
    title: 'Fibra Internet',
    amount: 29.9,
    category: 'utilities',
    frequency: 'monthly',
    profileId: 'p2',
    nextDueDate: '2026-10-05',
    enableAlert: false,
    includeInCalendar: false,
    status: 'due',
  },
];
