export const INITIAL_DOCUMENTS = [
  {
    id: 'doc-1',
    title: "Carta d'Identità Elettronica",
    type: 'idCard',
    profileId: 'p1',
    identifier: 'CA12345AA',
    issuer: 'Comune di Roma',
    issueDate: '2021-10-15',
    expiryDate: '2026-10-15',
    enableAlert: true,
    alertDays: 45,
    notes: 'Rinnovo da prenotare su CIE Online',
  },
  {
    id: 'doc-2',
    title: 'Patente di Guida B',
    type: 'drivingLicense',
    profileId: 'p1',
    identifier: 'U19283748K',
    issuer: 'MIT - UCO',
    issueDate: '2017-04-10',
    expiryDate: '2027-04-10',
    enableAlert: true,
    alertDays: 60,
    notes: 'Visita medica presso autoscuola',
  },
  {
    id: 'doc-3',
    title: 'Tessera Sanitaria',
    type: 'healthCard',
    profileId: 'p2',
    identifier: '803800012345678',
    issuer: 'Agenzia delle Entrate',
    issueDate: '2020-11-01',
    expiryDate: '2026-11-01',
    enableAlert: true,
    alertDays: 30,
    notes: 'Arriva automaticamente per posta',
  },
];
