export const SEED_WORK_EXPENSES = [
  {
    id: 'exp-12',
    title: 'RC Professionale',
    amount: 380,
    category: 'insurance',
    frequency: 'annual',
    profileId: 'p3',
    nextDueDate: '2026-12-28',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-13',
    title: 'Iscrizione Albo',
    amount: 180,
    category: 'work',
    frequency: 'annual',
    profileId: 'p3',
    nextDueDate: '2027-02-28',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
  {
    id: 'exp-14',
    title: 'Software & Cloud',
    amount: 290,
    category: 'subscriptions',
    frequency: 'annual',
    profileId: 'p3',
    nextDueDate: '2026-11-30',
    enableAlert: true,
    includeInCalendar: false,
    status: 'due',
  },
  {
    id: 'exp-15',
    title: 'Commercialista',
    amount: 300,
    category: 'work',
    frequency: 'quarterly',
    profileId: 'p3',
    nextDueDate: '2026-11-15',
    enableAlert: true,
    includeInCalendar: true,
    status: 'due',
  },
];
